<block> ::= <stmt> ";" | <stmt> ";" <block>
<namespace> ::= "namespace" "{" <block>? "}"
<subs> ::= <lhs> "=" <postfix_rhs>
<lhs> ::= <id> | "exp" | "_"
<postfix_rhs> ::= <rhs> | <postfix_rhs> "." <id>
<rhs> ::= <namespace> | <literal> | <subs> | <callable_or_type_rhs> | <call>
<stmt> ::= <subs> | "stmt"
<class_decl> ::= "class" "(" <decl_arg_list>? ")" "{" <block>? "}"
<arg_list> ::= <arg> | <arg_list> "," <arg>
<arg> ::= <postfix_rhs>
<decl_arg_list> ::= <decl_arg> | <decl_arg_list> "," <decl_arg>
<decl_arg> ::= <id> " " <callable_or_type_rhs>
<primitive_type> ::= "int" | "float"
<func_decl> ::= "(" <decl_arg_list>? ")" "{" <block>? "}"
<callable_or_type_rhs> ::= <id> | <func_decl> | <primitive_type> | <class_decl>
<call> ::= <callable_or_type_rhs> "(" <arg_list>? ")"
<literal> ::= "STR" | "NUM"
<id> ::= "ID"
